apiVersion: kubedb.com/v1alpha2
kind: Druid
metadata:
  name: druid-quickstart
  namespace: demo
spec:
#  version: 30.0.0
  version: 28.0.1
  deepStorage:
    type: s3
    configSecret:
      name: deep-storage-config
#  metadataStorage:
#    type: PostgreSQL
#    name: my-group
#    externallyManaged: true
#  zookeeperRef:
#    name: zk-demo
#    externallyManaged: true
  enableSSL: true
  tls:
    issuerRef:
      apiGroup: cert-manager.io
      kind: Issuer
      name: mysql-issuer
    certificates:
      - alias: server
        subject:
          organizations:
            - kubedb:server
        dnsNames:
          - localhost
        ipAddresses:
          - "127.0.0.1"
  topology:
    routers:
      replicas: 1
#  monitor:
#    agent: prometheus.io/operator
#    prometheus:
#      serviceMonitor:
#        labels:
#          release: prometheus
#        interval: 10s
#    overlords:
#      replicas: 1