apiVersion: kubedb.com/v1alpha2
kind: Druid
metadata:
  name: druid-quickstart
  namespace: demo
spec:
  version: 28.0.1
  deepStorage:
    type: s3
    configSecret:
      name: deep-storage-config
  metadataStorage:
    type: PostgreSQL
#    type: MySQL
#    name: my-group
#    name: demo-pg
#    namespace: demo
#    externallyManaged: true
#    createTables: true
#  zookeeperRef:
#    name: zk-demo
#    namespace: demo
#    externallyManaged: true
  topology:
    routers:
      replicas: 1
#    coordinators:
#      replicas: 1
#      podTemplate:
#        spec:
#          initContainers:
#            init-druid:
#              imagePullPolicy: Always
  monitor:
    agent: prometheus.io/operator
    prometheus:
      serviceMonitor:
        labels:
          release: prometheus
        interval: 10s
