apiVersion: kubedb.com/v1alpha2
kind: Druid
metadata:
  name: druid-quickstart
#  name: sample-druid
  namespace: demo
spec:
  version: 30.0.0
  deepStorage:
    type: s3
    configSecret:
      name: deep-storage-config
#  metadataStorage:
#    name: my-group
#    namespace: demo
#    externallyManaged: true
#    type: PostgreSQL
  #    name: demo-pg
  #    namespace: demo
  #    createTables: true
#    namespace: demo
#  zookeeperRef:
#    name: zk-demo
#    namespace: demo
#    externallyManaged: true
  topology:
    routers:
      replicas: 1
#    coordinators:
#      replicas: 2
#      podTemplate:
#        spec:
#          initContainers:
#            init-druid:
#              imagePullPolicy: Always