apiVersion: kubedb.com/v1alpha2
kind: Druid
metadata:
  name: druid-quickstart
  namespace: demo
spec:
  version: 30.0.0
  deepStorage:
    type: s3
    configSecret:
      name: deep-storage-config
  metadataStorage:
    name: my-group
    externallyManaged: true
#    type: PostgreSQL
  #    name: demo-pg
  #    namespace: demo
  #    createTables: true
#    namespace: demo
  zookeeperRef:
    name: zk-demo
    externallyManaged: true
  topology:
    routers:
      replicas: 1
    #  deletionPolicy: Halt
#    coordinators:
#      replicas: 2
#      podTemplate:
#        spec:
#          initContainers:
#            init-druid:
#              imagePullPolicy: Always