apiVersion: kubedb.com/v1alpha2
kind: Druid
metadata:
  name: druid-quickstart
  namespace: demo
spec:
  version: 28.0.1
  deepStorage:
    type: s3
    configSecret:
      name: deep-storage-config
  metadataStorage:
#    name: some-mysql
    name: demo-pg
    namespace: demo
    createTables: true
  zookeeperRef:
    name: zookeeper
    namespace: demo
  topology:
    routers:
      replicas: 1
#    coordinators:
#      replicas: 1
#      podTemplate:
#        spec:
#          initContainers:
#            init-druid:
#              imagePullPolicy: Always
