apiVersion: kubedb.com/v1alpha2
kind: ZooKeeper
metadata:
  name: zk-demo
  namespace: demo
spec:
  version: "3.7.2"
  adminServerPort: 8080
  replicas: 1
  storage:
    resources:
      requests:
        storage: "100Mi"
    accessModes:
      - ReadWriteOnce
  deletionPolicy: "WipeOut"