apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  annotations:
    meta.helm.sh/release-name: druid-minio
    meta.helm.sh/release-namespace: demo
  labels:
    app: minio
    app.kubernetes.io/managed-by: Helm
  name: myminio
  namespace: demo
spec:
  buckets:
  - name: druid
  configuration:
    name: myminio-env-configuration
  features:
    bucketDNS: false
    enableSFTP: false
  image: quay.io/minio/minio:RELEASE.2024-11-07T00-52-20Z
  imagePullPolicy: IfNotPresent
  mountPath: /export
  podManagementPolicy: Parallel
  pools:
  - name: default
    servers: 1
    volumeClaimTemplate:
      metadata:
        name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
    volumesPerServer: 1
  poolsMetadata:
    annotations: {}
    labels: {}
  prometheusOperator: false
  requestAutoCert: false
  subPath: /data
