apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: myminio-binding
  namespace: demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: myminio-role
subjects:
- kind: ServiceAccount
  name: myminio-sa
  namespace: demo
