apiVersion: v1
kind: Secret
metadata:
  name: myminio-env-configuration
  namespace: demo
type: Opaque
data:
  config.env: ZXhwb3J0IE1JTklPX1JPT1RfVVNFUj0ibWluaW8iCmV4cG9ydCBNSU5JT19ST09UX1BBU1NXT1JEPSJtaW5pbzEyMyI=
