apiVersion: v1
kind: Service
metadata:
  name: myminio-hl
  namespace: demo
spec:
  clusterIP: None
  selector:
    v1.min.io/tenant: myminio
  ports:
    - name: http-minio
      port: 9000
      targetPort: 9000
  type: ClusterIP
