apiVersion: kubedb.com/v1alpha2
kind: Druid
metadata:
  name: druid-webinar
  namespace: demo
spec:
  deepStorage:
    configSecret:
      name: deep-storage-config
    type: s3
  topology:
    routers:
      replicas: 1
  version: 28.0.1