data:
  data.sql: CREATE DATABASE druid;
metadata:
  name: druid-quickstart-init-script
  namespace: demo
  ownerReferences:
  - apiVersion: kubedb.com/v1alpha2
    blockOwnerDeletion: true
    controller: true
    kind: Druid
    name: druid-quickstart
    uid: 57fd63b8-a6c7-4637-bd0b-64ad06f97338
