apiVersion: ops.kubedb.com/v1alpha1
kind: DruidOpsRequest
metadata:
  name: druid-recon-tls
  namespace: demo
spec:
  type: ReconfigureTLS
  databaseRef:
    name: druid-quickstart
  tls:
    issuerRef:
      name: mysql-issuer
      kind: Issuer
      apiGroup: "cert-manager.io"
    certificates:
      - alias: client
        subject:
          organizations:
            - druid
          organizationalUnits:
            - client