apiVersion: ops.kubedb.com/v1alpha1
kind: DruidOpsRequest
metadata:
  name: druid-recon-tls-rmv
  namespace: demo
spec:
  type: ReconfigureTLS
  databaseRef:
    name: druid-quickstart
  tls:
    remove: true