apiVersion: ops.kubedb.com/v1alpha1
kind: DruidOpsRequest
metadata:
  name: volume-expansion-online-3gi
  namespace: demo
spec:
  type: VolumeExpansion
  databaseRef:
    name: druid-quickstart
  volumeExpansion:
    mode: "Online"
    middleManagers: 4Gi
    historicals: 4Gi
