apiVersion: ops.kubedb.com/v1alpha1
kind: DruidOpsRequest
metadata:
  name: volume-expansion-offline
  namespace: demo
spec:
  type: VolumeExpansion
  databaseRef:
    name: druid-quickstart
  volumeExpansion:
    mode: "Offline"
    middleManagers: 5Gi
    historicals: 5Gi
