apiVersion: ops.kubedb.com/v1alpha1
kind: DruidOpsRequest
metadata:
  name: druid-vscale
  namespace: demo
spec:
  type: VerticalScaling
  databaseRef:
    name: druid-quickstart
  verticalScaling:
#    routers:
#      resources:
#        limits:
#          memory: 1Gi
#        requests:
#          cpu: 600m
#          memory: 1Gi
#    middleManagers:
#      resources:
#        limits:
#          memory: 2560Mi
#        requests:
#          cpu: 900m
#          memory: 2560Mi
#    historicals:
#      resources:
#        limits:
#          memory: 2Gi
#        requests:
#          cpu: 500m
#          memory: 1Gi
#    brokers:
#      resources:
#        limits:
#          memory: 1Gi
#        requests:
#          cpu: 600m
#          memory: 1Gi
#    coordinators:
#      resources:
#        limits:
#          memory: 1Gi
#        requests:
#          cpu: 600m
#          memory: 1Gi