apiVersion: kubedb.com/v1alpha2
kind: MySQL
metadata:
  name: my-group
  namespace: demo
spec:
  terminationPolicy: WipeOut
  coordinator:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      runAsGroup: 0
      runAsNonRoot: true
      runAsUser: 1000670000
      seccompProfile:
        type: RuntimeDefault
  monitor:
    agent: prometheus.io/operator
    prometheus:
      exporter:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          runAsGroup: 0
          runAsNonRoot: true
          runAsUser: 1000670000
          seccompProfile:
            type: RuntimeDefault
      serviceMonitor:
        interval: 30s
        labels:
          release: kube-prometheus-stack
  podTemplate:
    spec:
      containerSecurityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        runAsGroup: 0
        runAsNonRoot: true
        runAsUser: 1000670000
        seccompProfile:
          type: RuntimeDefault
      securityContext:
        fsGroup: 1000670000
      initContainers:
        - name: mysql-init
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsGroup: 0
            runAsNonRoot: true
            runAsUser: 1000670000
            seccompProfile:
              type: RuntimeDefault
  replicas: 3
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
  storageType: Durable
  topology:
    mode: GroupReplication
  version: 8.2.0