apiVersion: core.kubestash.com/v1alpha1
kind: RestoreSession
metadata:
  name: sample-restore
  namespace: demo
spec:
  manifestOptions:
    restoreNamespace: demo2
    druid:
      db: true
      dbName: new-db
      deepStorageSecret: true
      #authSecret: true
#      authSecretName: tapo-auth
      #configSecret: true
      metadataStorage:
        restore: true
      zooKeeper:
        restore: true
#        name: pg-demo
#        namespace: demo2
#      zooKeeper:
#        name: zk-demo
#        namespace: demo2
  dataSource:
    snapshot: latest
    repository: s3-repo
    encryptionSecret:
      name: encry-secret # some addon may not support encryption
      namespace: demo
  addon:
    name: druid-addon
    tasks:
#      - name: logical-backup-restore
      - name: manifest-restore