apiVersion: core.kubestash.com/v1alpha1
kind: RestoreSession
metadata:
  name: sample-restore
  namespace: demo3
spec:
  manifestOptions:
    restoreNamespace: demo
    druid:
      db: true
      dbName: new-db
      authSecretName: tapo-auth
      #configSecret: true
    mySQL:
      db: true
      authSecret: true
      authSecretName: xoxo
    zooKeeper:
      db: true
      authSecret: true
      authSecretName: pppp
  dataSource:
    snapshot: latest
    repository: s3-repo
    encryptionSecret:
      name: encry-secret # some addon may not support encryption
      namespace: demo
  addon:
    name: druid-addon
    tasks:
      #      - name: logical-backup-restore
      - name: manifest-restore